name: Build Emre Baba APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Derleme işlemi
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v3

      - name: Java kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle izin ver
        run: chmod +x ./gradlew

      - name: APK oluştur
        run: ./gradlew assembleDebug

      - name: APK çıktısını yükle
        uses: actions/upload-artifact@v3
        with:
          name: Emre-Baba-APK
          path: app/build/outputs/apk/debug/*.apk
